### ISSUE TITLE
翻译时无法正确处理图片

### ISSUE THREAD

**Issue by qwIvan** [macacajs/macaca-bot#2]
![_ _20180610051618](https://user-images.githubusercontent.com/7613160/41196196-7280e2b6-6c6d-11e8-92fe-032f419900fe.png)
如图

**Comment by xudafeng** [comment]
@qwIvan 来个pr试试？

**Comment by gaius-qi** [comment]
我来看一看

**Comment by xudafeng** [comment]
验证消息

**Comment by xudafeng** [comment]
验证消息

**Comment by xudafeng** [comment]
验证消息

**Comment by xudafeng** [comment]
验证消息

**Comment by xudafeng** [comment]
This is the translated issue comment: @xudafeng

<hr/>

verification message

**Comment by gaius-qi** [comment]
我来看看

**Comment by gaius-qi** [comment]
我来看看

**Comment by xudafeng** [comment]
This is the translated issue comment: @gaius-qi

<hr/>

Let me see

**Comment by xudafeng** [comment]
This is the translated issue comment: @xudafeng

<hr/>

verification message

**Comment by xudafeng** [comment]
验证

**Comment by xudafeng** [comment]
This is the translated issue comment: @xudafeng

<hr/>

verification

**Comment by xudafeng** [comment]
稳定性验证

**Comment by xudafeng** [comment]
稳定性验证

**Comment by xudafeng** [comment]
验证

**Comment by xudafeng** [comment]
验证回复

**Comment by xudafeng** [comment]
服务预备

**Comment by gaius-qi** [comment]
我来看看

**Comment by xudafeng** [comment]
验证消息

**Comment by xudafeng** [comment]
验证一次

**Comment by xudafeng** [comment]
开始验证

**Comment by xudafeng** [comment]
再来一次

**Comment by gaius-qi** [comment]
再来一次

**Comment by xudafeng** [comment]
再次验证

**Comment by xudafeng** [comment]
验证正式开关

**Comment by paradite** [comment]
test:
![_ _20180610051618](https://user-images.githubusercontent.com/7613160/41196196-7280e2b6-6c6d-11e8-92fe-032f419900fe.png)

**Comment by paradite** [comment]
looks like it is missing a `!` in the markdown syntax, will fix soon.
